# coding: utf-8

"""
    Basecamp4 API

    This is an API schema for the Basecamp4 API. It is used to generate client libraries to interact with the API.

    The version of the OpenAPI document: 1.0.0
    Contact: barry@wstrategies.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from basecamp4_python_sdk.models.card_create_request import CardCreateRequest

class TestCardCreateRequest(unittest.TestCase):
    """CardCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CardCreateRequest:
        """Test CardCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CardCreateRequest`
        """
        model = CardCreateRequest()
        if include_optional:
            return CardCreateRequest(
                title = '',
                content = '',
                due_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                notify = True
            )
        else:
            return CardCreateRequest(
                title = '',
        )
        """

    def testCardCreateRequest(self):
        """Test CardCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
