# coding: utf-8

"""
    Basecamp4 API

    This is an API schema for the Basecamp4 API. It is used to generate client libraries to interact with the API.

    The version of the OpenAPI document: 1.0.0
    Contact: barry@wstrategies.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from basecamp4_python_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_card_table_card(self) -> None:
        """Test case for create_card_table_card

        Create a card
        """
        pass

    def test_get_authorization(self) -> None:
        """Test case for get_authorization

        Get authorization
        """
        pass

    def test_get_card_table(self) -> None:
        """Test case for get_card_table

        Get card table
        """
        pass

    def test_get_card_table_cards(self) -> None:
        """Test case for get_card_table_cards

        Get card table cards
        """
        pass

    def test_get_card_table_column(self) -> None:
        """Test case for get_card_table_column

        Get card table column
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        Get projects
        """
        pass

    def test_move_card_table_card(self) -> None:
        """Test case for move_card_table_card

        Move a card
        """
        pass

    def test_update_card_table_card(self) -> None:
        """Test case for update_card_table_card

        Update a card
        """
        pass


if __name__ == '__main__':
    unittest.main()
