version: "3.9"

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8088:8080"
    volumes:
      - ./schema:/tmp
    environment:
      - SWAGGER_FILE=/tmp/schema.yaml
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8089:80"
