# coding: utf-8

# flake8: noqa
"""
    Basecamp4 API

    This is an API schema for the Basecamp4 API. It is used to generate client libraries to interact with the API.

    The version of the OpenAPI document: 1.0.0
    Contact: barry@wstrategies.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from basecamp4_python_sdk.models.account import Account
from basecamp4_python_sdk.models.authorization import Authorization
from basecamp4_python_sdk.models.dock_item import DockItem
from basecamp4_python_sdk.models.identity import Identity
from basecamp4_python_sdk.models.project import Project
