openapi: 3.0.3

info:
  title: Basecamp4 API
  version: 1.0.0
  description: This is an API schema for the Basecamp4 API. It is used to generate client libraries to interact with the API.
  contact:
    name: Barry Molina
    email: barry@wstrategies.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Basecamp4 API
  url: https://github.com/basecamp/bc3-api
servers:
  - url: https://3.basecampapi.com/{account_id}
    variables:
      account_id:
        description: Your Basecamp4 account ID (retrieve from the authorization endpoint)
        default: "9999999"
    description: Basecamp4 API
  - url: https://launchpad.37signals.com
    description: Basecamp4 API authentication
  - url: http://localhost:8089/launchpad
    description: Proxy server to 'https://launchpad.37signals.com' to avoid CORS issues
  - url: http://localhost:8089/basecampapi/{account_id}
    description: Proxy server to 'https://3.basecampapi.com' to avoid CORS issues
    variables:
      account_id:
        description: Your Basecamp4 account ID (retrieve from the authorization endpoint)
        default: "9999999"
security:
  - BearerAuth: []
paths:
  /authorization.json:
    get:
      operationId: getAuthorization
      summary: Get authorization
      description: Get the authorization for the Basecamp4 API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorization"
  /projects.json:
    get:
      operationId: getProjects
      summary: Get projects
      description: Get the projects for the Basecamp4 API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
  /buckets/{project_id}/card_tables/{card_table_id}.json:
    get:
      operationId: getCardTable
      summary: Get card table
      description: Get the card table for the Basecamp4 API
      parameters:
        - name: project_id
          in: path
          description: The project ID
          required: true
          schema:
            type: integer
        - name: card_table_id
          in: path
          description: The card table ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardTable"
        "404":
          description: Not Found
  /buckets/{project_id}/card_tables/columns/{column_id}.json:
    get:
      operationId: getCardTableColumn
      summary: Get card table column
      description: Get the card table column for the Basecamp4 API
      parameters:
        - name: project_id
          in: path
          description: The project ID
          required: true
          schema:
            type: integer
        - name: column_id
          in: path
          description: The card table column ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardTableColumn"
        "404":
          description: Not Found
  /buckets/{project_id}/card_tables/lists/{column_id}/cards.json:
    get:
      operationId: getCardTableCards
      summary: Get card table cards
      description: Get the card table cards for the Basecamp4 API
      parameters:
        - name: project_id
          in: path
          description: The project ID
          required: true
          schema:
            type: integer
        - name: column_id
          in: path
          description: The card table column ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardTableCard"
        "404":
          description: Not Found
    post:
      operationId: createCardTableCard
      summary: Create a card
      description: Creates a new card in the specified card table.
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
          description: The project ID.
        - name: column_id
          in: path
          required: true
          schema:
            type: integer
          description: The column ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardCreateRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardTableCard"
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /buckets/{project_id}/card_tables/cards/{card_id}.json:
    put:
      operationId: updateCardTableCard
      summary: Update a card
      description: Allows changing of the card with a specified ID in the project with a specified ID.
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
          description: The project ID.
        - name: card_id
          in: path
          required: true
          schema:
            type: integer
          description: The card ID.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardUpdateRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardTableCard"
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /buckets/{project_id}/card_tables/cards/{card_id}/moves.json:
    post:
      operationId: moveCardTableCard
      summary: Move a card
      description: Allows moving of a card to a different column within the same card table.
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
          description: The project ID.
        - name: card_id
          in: path
          required: true
          schema:
            type: integer
          description: The card ID to move.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardMoveRequest"
      responses:
        "204":
          description: No content
        "400":
          description: Bad Request
        "404":
          description: Not Found
components:
  schemas:
    Authorization:
      type: object
      properties:
        expires_at:
          type: string
          format: date-time
        identity:
          $ref: "#/components/schemas/Identity"
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/Account"
    Identity:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email_address:
          type: string
    Account:
      type: object
      properties:
        product:
          type: string
        id:
          type: integer
        name:
          type: string
        href:
          type: string
        app_href:
          type: string
    DockItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the dock item
        title:
          type: string
          description: Display title of the dock item
        name:
          type: string
          description: System name of the dock item
        enabled:
          type: boolean
          description: Indicates if the dock item is enabled
        position:
          type: integer
          format: int32
          description: Position of the dock item in the UI, null if not applicable
          nullable: true
        url:
          type: string
          format: uri
          description: API URL for the dock item
        app_url:
          type: string
          format: uri
          description: Web application URL for the dock item
      required:
        - id
        - title
        - name
        - enabled
        - url
        - app_url
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the project
        status:
          type: string
          description: Current status of the project
        created_at:
          type: string
          format: date-time
          description: Timestamp of project creation
        updated_at:
          type: string
          format: date-time
          description: Timestamp of last project update
        name:
          type: string
          description: Name of the project
        description:
          type: string
          description: Detailed description of the project
        purpose:
          type: string
          description: Purpose of the project
        clients_enabled:
          type: boolean
          description: Indicates if clients are enabled for the project
        bookmark_url:
          type: string
          format: uri
          description: URL for bookmarking the project
        url:
          type: string
          format: uri
          description: API URL for the project
        app_url:
          type: string
          format: uri
          description: Web application URL for the project
        dock:
          type: array
          items:
            $ref: "#/components/schemas/DockItem"
          description: Collection of dock items associated with the project
        bookmarked:
          type: boolean
          description: Indicates if the project is bookmarked
      required:
        - id
    CardTable:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        visible_to_clients:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        title:
          type: string
        inherits_status:
          type: boolean
        type:
          type: string
        url:
          type: string
          format: uri
        app_url:
          type: string
          format: uri
        bookmark_url:
          type: string
          format: uri
        subscription_url:
          type: string
          format: uri
        bucket:
          $ref: "#/components/schemas/Bucket"
        creator:
          $ref: "#/components/schemas/Person"
        subscribers:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        lists:
          type: array
          items:
            $ref: "#/components/schemas/CardTableColumn"
      required:
        - id
    Bucket:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
      required:
        - id
    Person:
      type: object
      properties:
        id:
          type: integer
        attachable_sgid:
          type: string
        name:
          type: string
        email_address:
          type: string
        personable_type:
          type: string
        title:
          type: string
        bio:
          type: string
        location:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        admin:
          type: boolean
        owner:
          type: boolean
        client:
          type: boolean
        employee:
          type: boolean
        time_zone:
          type: string
        avatar_url:
          type: string
          format: uri
        company:
          $ref: "#/components/schemas/Company"
        can_manage_projects:
          type: boolean
        can_manage_people:
          type: boolean
      required:
        - id
    Company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
    CardTableColumn:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        visible_to_clients:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        title:
          type: string
        inherits_status:
          type: boolean
        type:
          type: string
        url:
          type: string
          format: uri
        app_url:
          type: string
          format: uri
        bookmark_url:
          type: string
          format: uri
        parent:
          $ref: "#/components/schemas/CardTable"
        bucket:
          $ref: "#/components/schemas/Bucket"
        creator:
          $ref: "#/components/schemas/Person"
        description:
          type: string
        subscribers:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        color:
          type: string
        cards_count:
          type: integer
        comment_count:
          type: integer
        cards_url:
          type: string
          format: uri
      required:
        - id
    CardTableCard:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        visible_to_clients:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        title:
          type: string
        inherits_status:
          type: boolean
        type:
          type: string
        url:
          type: string
          format: uri
        app_url:
          type: string
          format: uri
        bookmark_url:
          type: string
          format: uri
        subscription_url:
          type: string
          format: uri
        comments_count:
          type: integer
        comments_url:
          type: string
          format: uri
        position:
          type: integer
        parent:
          $ref: "#/components/schemas/CardTableColumn"
        bucket:
          $ref: "#/components/schemas/Bucket"
        creator:
          $ref: "#/components/schemas/Person"
        description:
          type: string
        completed:
          type: boolean
        content:
          type: string
        due_on:
          type: string
          format: date
          nullable: true
        assignees:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        completion_subscribers:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        completion_url:
          type: string
          format: uri
        comment_count:
          type: integer
      required:
        - id
    CardCreateRequest:
      type: object
      properties:
        title:
          type: string
          description: Title of the card.
        content:
          type: string
          description: Content containing information about the card. See Basecamp Rich text guide for what HTML tags are allowed.
        due_on:
          type: string
          format: date
          description: Due date (ISO 8601) of the card.
        notify:
          type: boolean
          default: false
          description: Whether to notify assignees, value true or false. Defaults to false.
      required:
        - title
    CardMoveRequest:
      type: object
      required:
        - column_id
      properties:
        column_id:
          type: integer
          description: The column ID of the destination column.

    CardUpdateRequest:
      type: object
      properties:
        title:
          type: string
          description: Title of the card.
        content:
          type: string
          description: Content containing information about the card. See Basecamp Rich text guide for what HTML tags are allowed.
        due_on:
          type: string
          format: date
          description: Due date (ISO 8601) of the card.
        assignee_ids:
          type: array
          items:
            type: integer
          description: An array of people that will be assigned to this card. Please see the Get people endpoints to retrieve them.

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
